[tool.poetry]
name = "MeowerBot"
version = "1.3.2"
description = "A meower bot lib for py"
authors = ["showierdata9978 <68120127+showierdata9978@users.noreply.github.com>"]
license = "MEOW"
readme = "README.md"
packages = [
    {include = "MeowerBot", from = "src"}
]
repository = "https://github.com/showierdata9978/MeowerBot"


[tool.poetry.dependencies]
python = "^3.10"
meower = "^0.0.6"
cloudlink = "^0.1.7"
requests = "^2.28.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
