[tool.poetry]
name = "MeowerBot"
version = "2.6.3"
description = "A meower bot lib for py"
authors = ["showierdata9978 <68120127+showierdata9978@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "MeowerBot"}
]
repository = "https://github.com/MeowerBots/MeowerBot.py"


[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.0"
websocket-client = "*"
backports-strenum = { version = "^1.2.4", python = "<3.11" }

[tool.poetry.group.extras.dependencies]



[tool.poetry.group.dev.dependencies]
bandit = "^1.7.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
